version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 020046395185.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nginx:latest .
      - docker tag nginx:latest 020046395185.dkr.ecr.us-east-1.amazonaws.com/nginx:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 020046395185.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
      - printf '{"ImageURI":"%s"}' 020046395185.dkr.ecr.us-east-1.amazonaws.com/nginx:latest  > imageDetail.json
      - sed -i 's/<APP_NAME>/'nginx'/g' appspec.yml taskdef.json
      - sed -i 's/<SERVICE_PORT>/'80'/g' appspec.yml taskdef.json
      - sed -i 's/<AWS_ACCOUNT_ID>/'020046395185'/g' taskdef.json
      - sed -i 's/<MEMORY_RESV>/'128'/g' taskdef.json
      - sed -i 's/<IMAGE_NAME>/'020046395185'\.dkr\.ecr\.'us-east-1'\.amazonaws.com\/'nginx'\:'latest'/g' taskdef.json
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json